export const ADD_VAULT_REQUEST = 'ADD_VAULT_REQUEST';
export const ADD_VAULT_SUCCESS = 'ADD_VAULT_SUCCESS';
export const ADD_VAULT_FAILURE = 'ADD_VAULT_FAILURE';

export const FETCH_VAULTS_REQUEST = 'FETCH_VAULTS_REQUEST';
export const FETCH_VAULTS_SUCCESS = 'FETCH_VAULTS_SUCCESS';
export const FETCH_VAULTS_FAILURE = 'FETCH_VAULTS_FAILURE';

export const FETCH_VAULT_REQUEST = 'FETCH_VAULT_REQUEST';
export const FETCH_VAULT_SUCCESS = 'FETCH_VAULT_SUCCESS';
export const FETCH_VAULT_FAILURE = 'FETCH_VAULT_FAILURE';

export const DELETE_VAULT_REQUEST = 'DELETE_VAULT_REQUEST';
export const DELETE_VAULT_SUCCESS = 'DELETE_VAULT_SUCCESS';
export const DELETE_VAULT_FAILURE = 'DELETE_VAULT_FAILURE';

export const PATCH_VAULT_REQUEST = 'PATCH_VAULT_REQUEST';
export const PATCH_VAULT_SUCCESS = 'PATCH_VAULT_SUCCESS';
export const PATCH_VAULT_FAILURE = 'PATCH_VAULT_FAILURE';

// Category
export const ADD_CATEGORY_REQUEST = 'ADD_CATEGORY_REQUEST';
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';
export const ADD_CATEGORY_FAILURE = 'ADD_CATEGORY_FAILURE';

export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';    

// Application
export const SHOW_PROMPT = 'SHOW_PROMPT';
export const CLOSE_PROMPT = 'CLOSE_PROMPT';
